version: '3.8'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - toxsl-network
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toxsl_base
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
    ports:
      - "42333:3306"
    volumes:
      - "./mysql/db:/var/lib/mysql"
    networks:
      - toxsl-network

networks:
  toxsl-network:
    driver: bridge
